# Welcome to your prefect.yaml file! You can use this file for storing and managing
# configuration for deploying your flows. We recommend committing this file to source
# control along with your flow code.

# Generic metadata about this project
name: CTDC DATAOPS
prefect-version: null

# build section allows you to manage and build docker images
build: null

# push section allows you to manage if and how this project is uploaded to remote locations
push: null

# pull section allows you to provide instructions for cloning this project in remote locations
pull:
  - prefect.deployments.steps.git_clone:
      id: clone-step
      repository: https://github.com/CBIIT/ctos-dataops-pipelines.git
      branch: dataops_ctdc_pipelines
      include_submodules: True
  - prefect.deployments.steps.pip_install_requirements:
      requirements_file: requirements.txt
      directory: "{{ clone-step.directory }}"
      stream_output: False

deployments:
  - name: ctos-dataops-neo4j-summary
    version: null
    tags: []
    description: null
    schedule: {}
    flow_name: null
    entrypoint:  neo4j_summary_prefect.py:neo4j_summary_prefect
    parameters:
      neo4j_ip: ""
      neo4j_user: ""
      neo4j_password: ""
      s3_bucket: "{{ prefect.variables.cds_dataops_bucket }}"
      s3_folder: ""
      neo4j_summary_file_name: neo4j_summary.json
    work_pool:
        name: cds-curation-ecs
        work_queue_name: cds-curation-queue
        job_variables:
          env:
            PREFECT_LOGGING_EXTRA_LOGGERS: "Neo4j Summary Generator, S3 Bucket, Bento Config"

  - name: ctos-dataops-neo4j-secret-summary
    version: null
    tags: []
    description: null
    schedule: {}
    flow_name: null
    entrypoint:  neo4j_summary_prefect.py:neo4j_secret_summary_prefect
    parameters:
      secret_name: "{{ prefect.variables.secret_name_dev_neo4j_summary }}"
      s3_bucket: "{{ prefect.variables.cds_dataops_bucket }}"
      s3_folder: ""
      neo4j_summary_file_name: neo4j_summary.json
    work_pool:
      name: cds-curation-ecs
      work_queue_name: cds-curation-queue
      job_variables:
        env:
          PREFECT_LOGGING_EXTRA_LOGGERS: "Neo4j Summary Generator, S3 Bucket, Bento Config"
    
  - name: ctos-dataops-data-model-archiving
    version: null
    tags: []
    description: null
    schedule: {}
    flow_name: null
    entrypoint:  data_model_archiving_prefect.py:data_model_archiving_prefect
    parameters:
      data_model_repo_url: ""
      data_model_version: ""
      s3_bucket: "{{ prefect.variables.cds_dataops_bucket }}"
      s3_prefix: ""
    work_pool:
      name: cds-curation-ecs
      work_queue_name: cds-curation-queue
      job_variables:
        env:
          PREFECT_LOGGING_EXTRA_LOGGERS: "Data Model Archiving, S3 Bucket, Bento Config"
  
  - name: ctos-dataops-neo4j-dump
    version: null
    tags: []
    description: null
    schedule: {}
    flow_name: null
    entrypoint:  neo4j_dump_prefect.py:neo4j_dump_prefect
    parameters:
      secret_name_ssh: ""
      secret_name: ""
      s3_bucket: "{{ prefect.variables.cds_dataops_bucket }}"
      s3_folder: ""
      dump_file_name: "test_dump.dump"
    work_pool:
      # replace 
      name: cds-curation-ecs
      work_queue_name: cds-curation-queue
      job_variables:
        env:
          PREFECT_LOGGING_EXTRA_LOGGERS: "Neo4j Dump Generator, S3 Bucket, Bento Config"
# change each under here 
  - name: ctdc-dataops-neo4j-generation-loading
    version: null
    tags: []
    description: null
    schedule: {}
    flow_name: null
    entrypoint:  data_asset_generation_prefect.py:data_asset_generation_prefect
    parameters:
      data_model_version: "{{ prefect.variables.cds_model_version }}"
      s3_folder: ""
      neo4j_summary_file_name: neo4j_summary.json
      neo4j_dump_file_name: neo4j_dump.dump
      data_model_repo_url: "{{ prefect.variables.cds_model_repo_url }}"
      s3_bucket: "{{ prefect.variables.cds_dataops_bucket }}"
    work_pool:
      name: crdc-curation-16gb-prefect-3.2.14-python3.9
      work_queue_name: default
      job_variables:
        env:
          PREFECT_LOGGING_EXTRA_LOGGERS: "Neo4j Summary Generator, Data Model Archiving, Neo4j Dump Generator, S3 Bucket, Bento Config"
  
  - name: ctdc-dataops-neo4j-asset-loading
    version: null
    tags: []
    description: null
    schedule: {}
    flow_name: null
    entrypoint:  data_asset_loading_prefect.py:data_asset_loading_prefect
    parameters:
      s3_folder: ""
      dump_file_name: "neo4j_dump.dump"
      validation_summary_file_name: "neo4j_summary.json"
      restore_summary_file_name: "neo4j_restore_summary.json"
      s3_bucket: "{{ prefect.variables.cds_dataops_bucket }}"
    work_pool:
      name: crdc-curation-16gb-prefect-3.2.14-python3.9
      work_queue_name: default
      job_variables:
        env:
          PREFECT_LOGGING_EXTRA_LOGGERS: "Neo4j Summary Generator, Neo4j Data Asset Loading, Neo4j Restore, S3 Bucket, Bento Config"
  
  - name: ctdc-dataops-memgraph-asset-generation
    version: null
    tags: []
    description: null
    schedule: {}
    flow_name: null
    entrypoint:  memgraph_data_asset_generation_prefect.py:memgraph_data_asset_generation_prefect
    parameters:
      s3_folder: ""
      s3_bucket: "ctdc-nonprod-prefect-dedicated-bucket"
      tmp_folder: "/tmp"
      data_model_version: "{{ prefect.variables.cds_model_version }}"
      data_model_repo_url: "{{ prefect.variables.cds_model_repo_url }}"
      memgraph_summary_file_name: memgraph_summary.json
      memgraph_dump_file_name: memgraph_dump.cypherl
    work_pool:
      name: crdc-curation-16gb-prefect-3.2.14-python3.9
      work_queue_name: default
      job_variables:
        env:
          PREFECT_LOGGING_EXTRA_LOGGERS: "Memgraph Data Asset Generation, Neo4j Summary Generator, Data Model Archiving"

  - name: ctdc-dataops-memgraph-asset-loading
    version: null
    tags: []
    description: null
    schedule: {}
    flow_name: null
    entrypoint:  memgraph_data_asset_loading_prefect.py:memgraph_data_asset_loading_prefect
    parameters:
      s3_folder: ""
      s3_bucket: "{{ prefect.variables.cds_dataops_bucket }}"
      tmp_folder: "/tmp"
      memgraph_validation_summary_file_name: memgraph_summary.json
      memgraph_restore_summary_file_name: memgraph_restore_summary.json
      memgraph_dump_file_name: memgraph_dump.cypherl
    work_pool:
      name: crdc-curation-16gb-mgconsole-prefect-3.4.18-python3.12
      work_queue_name: default
      job_variables:
        env:
          PREFECT_LOGGING_EXTRA_LOGGERS: "Memgraph Data Asset Loading, Neo4j Summary Generator"

  - name: ctdc-dataops-memgraph-asset-loading-prod
    version: null
    tags: []
    description: null
    schedule: {}
    flow_name: null
    entrypoint:  memgraph_data_asset_loading_prefect.py:memgraph_data_asset_loading_prefect
    parameters:
      s3_folder: ""
      s3_bucket: "{{ prefect.variables.gc_prod_bucket }}"
      tmp_folder: "/tmp"
      memgraph_validation_summary_file_name: memgraph_summary.json
      memgraph_restore_summary_file_name: memgraph_restore_summary.json
      memgraph_dump_file_name: memgraph_dump.cypherl
    work_pool:
      name: crdc-curation-16gb-prefect-3.2.14-python3.9
      work_queue_name: default
      job_variables:
        env:
          PREFECT_LOGGING_EXTRA_LOGGERS: "Memgraph Data Asset Loading, Neo4j Summary Generator"

  - name: ctdc-ctos-dataops-opensearch-backup
    version: null
    tags: []
    description: null
    schedule: {}
    flow_name: null
    entrypoint:  opensearch_backup_prefect.py:opensearch_backup_prefect
    parameters:
      environment: "ctdc_stage"
      snapshot_name: ""
      s3_bucket: "crdc-stage-ctdc-opensearch-snapshot-bucket"
      indices: ""
    work_pool:
      name: crdc-curation-8gb-crdc
      work_queue_name: default
      job_variables:
        env:
          PREFECT_LOGGING_EXTRA_LOGGERS: "OpenSearch Backup"

  - name: ctdc-ctos-dataops-opensearch-restore
    version: null
    tags: []
    description: null
    schedule: {}
    flow_name: null
    entrypoint:  opensearch_restore_prefect.py:opensearch_restore_prefect
    parameters:
      snapshot_name: ""
      s3_bucket: "crdc-stage-ctdc-opensearch-snapshot-bucket"
      indices: ""
    work_pool:
      name: crdc-curation-8gb-prefect-3.2.14-python3.9
      work_queue_name: default
      job_variables:
        env:
          PREFECT_LOGGING_EXTRA_LOGGERS: "OpenSearch Restore"
  - name: ctdc-ctos-dataops-opensearch-backup-prod
    version: null
    tags: []
    description: null
    schedule: {}
    flow_name: null
    entrypoint:  opensearch_backup_prefect.py:opensearch_backup_prefect
    parameters:
      environment: "ctdc_stage"
      snapshot_name: ""
      s3_bucket: "crdc-stage-ctdc-opensearch-snapshot-bucket"
      indices: ""
    work_pool:
      name: crdc-curation-prod-16gb-prefect-3.2.14-python3.9
      work_queue_name: default
      job_variables:
        env:
          PREFECT_LOGGING_EXTRA_LOGGERS: "OpenSearch Backup"
  - name: ctdc-ctos-dataops-opensearch-restore-prod
    version: null
    tags: []
    description: null
    schedule: {}
    flow_name: null
    entrypoint:  opensearch_restore_prefect.py:opensearch_restore_prefect
    parameters:
      snapshot_name: ""
      s3_bucket: "crdc-stage-ctdc-opensearch-snapshot-bucket"
      indices: ""
    work_pool:
      name: crdc-curation-prod-16gb-prefect-3.2.14-python3.9
      work_queue_name: default
      job_variables:
        env:
          PREFECT_LOGGING_EXTRA_LOGGERS: "OpenSearch Restore"
  
  - name: universal-dataops-opensearch-backup-ctdc-1
    version: null
    tags: []
    description: null
    schedule: {}
    flow_name: null
    entrypoint:  opensearch_backup_universal_prefect.py:opensearch_backup_prefect
    parameters:
      snapshot_name: ""
      secret_name_prefect_variable: ""
      aws_role_prefect_variable: ""
      opensearch_repo: "{{ prefect.variables.gc_opensearch_repo }}"
      s3_bucket: "crdc-stage-ctdc-opensearch-snapshot-bucket"
      indices: ""
    work_pool:
      name: crdc-curation-16gb-prefect-3.2.14-python3.9
      work_queue_name: default
      job_variables:
        env:
          PREFECT_LOGGING_EXTRA_LOGGERS: "OpenSearch Backup"
  
  - name: universal-dataops-opensearch-restore-ctdc
    version: null
    tags: []
    description: null
    schedule: {}
    flow_name: null
    entrypoint:  opensearch_restore_universal_prefect.py:opensearch_restore_prefect
    parameters:
      snapshot_name: ""
      secret_name_prefect_variable: ""
      aws_role_prefect_variable: ""
      opensearch_repo: "{{ prefect.variables.gc_opensearch_repo }}"
      s3_bucket: "crdc-stage-ctdc-opensearch-snapshot-bucket"
      indices: ""
    work_pool:
      name: crdc-curation-16gb-prefect-3.2.14-python3.9
      work_queue_name: default
      job_variables:
        env:
          PREFECT_LOGGING_EXTRA_LOGGERS: "OpenSearch Restore"
  
  - name: gc-ctos-dataops-s3-file-metadata-generator
    version: null
    tags: []
    description: null
    schedule: {}
    flow_name: null
    entrypoint:  s3_file_metadata_generator_prefect.py:s3_file_metadata_generator_prefect
    parameters:
      bucket_name: ""
      s3_subfolder: ""
      tsv_filename: "s3_object_metadata.tsv"
    work_pool:
      name: cds-general-mgconsole-prefect-3.4.18-python3.12
      work_queue_name: default
      job_variables:
        env:
          PREFECT_LOGGING_EXTRA_LOGGERS: "S3 File Metadata Generator"