neo4j_user: neo4j
neo4j_password: password
bolt_port: "bolt://localhost:7688"
nodes:
  - study
  - file
schema:
  - cds-model/model-desc/cds-model.yml
  - cds-model/model-desc/cds-model-props.yml
where:
  study.phs_accession:
    values:
      - phs002790
    where_connected: TRUE #do not need this value if the user do not want the where query affect the children nodes