popsci_dev:
  memgraph_summary_secret: "popsci_memgraph_secret_name_dev"
  env: dev
popsci_dev2:
  memgraph_summary_secret: "popsci_memgraph_secret_name_dev2"
  env: dev
popsci_qa:
  memgraph_summary_secret: "popsci_memgraph_secret_name_qa"
  env: dev
popsci_qa2:
  memgraph_summary_secret: "popsci_memgraph_secret_name_qa2"
  env: dev
popsci_stage:
  memgraph_summary_secret: "popsci_memgraph_secret_name_stage"
  env: stage
popsci_prod:
  memgraph_summary_secret: "popsci_memgraph_secret_name_prod"
  env: stage
